#!/bin/bash

# instance-functions.sh
#
# List, run, start, stop and ssh to Amazon AWS EC2 instances

# Fields to include when listing EC2 Instances
INSTANCE_OUTPUT="[InstanceId, State.Name, InstanceType, PrivateIpAddress, PublicIpAddress, join(\` \`, [Tags[?Key==\`Name\`].Value][]), join(\` \`, [Tags[?Key==\`contact\`].Value][]), LaunchTime]"

#  Fields to include when listing EBS volumes
VOLUME_OUTPUT='[VolumeId, Size, VolumeType, State, CreateTime]'

instances() {
  aws ec2 describe-instances $filters \
    --query "Reservations[].Instances[].${INSTANCE_OUTPUT}" \
    --output text
}

instance_list() {
  aws ec2 describe-instances --output=json |
    jq -r ".Reservations[].Instances[].InstanceId"
}

instance() {
  if [ -z "$1" ] ; then echo "Usage: $FUNCNAME instance-id [instance-id]"; return 1; fi
  aws ec2 describe-instances --instance-ids $@
}

instances_with_tag() {
  if [ -z "$1" ] ; then echo "Usage: $FUNCNAME tag_key [tag_value]"; return 1; fi
  local tag_name=$1
  local tag_value=${2:-*}
  aws ec2 describe-instances \
    --output json \
    --filters "Name=tag:${tag_name},Values=${tag_value}" |
      jq -r ".Reservations[].Instances[].InstanceId"
}

instances_without_tag() {
  if [ -z "$1" ] ; then echo "Usage: $FUNCNAME tag_key [tag_value]"; return 1; fi
  local tag_key=$1
  local tag_value=$2
  if [ -z "$tag_value" ]; then
    aws ec2 describe-instances --output text --query "Reservations[].Instances[?contains(Tags[].Key[], \`$tag_key\`) != \`true\`][].${INSTANCE_OUTPUT}"
  else
    aws ec2 describe-instances --output text --query "Reservations[].Instances[?contains(Tags[?Key==\`$tag_key\`].Value[], \`$tag_value\`) != \`true\`][].${INSTANCE_OUTPUT}"
  fi
}

alias instances_in_stack=cf_instances

instance_console_output() {
  if [ -z "$1" ] ; then echo "Usage: $FUNCNAME instance_id"; return 1; fi 
  local instance_id=$1
  aws ec2 get-console-output --instance-id $instance_id --query Output --output text
}

instance_role() {
  if [ -z "$1" ] ; then echo "Usage: $FUNCNAME instance_id"; return 1; fi
  local instance_id=$1
  local iam_instance_profile_id=$(aws ec2 describe-instances --instance-id $instance_id --query "Reservations[].Instances[].IamInstanceProfile.Id" --output text)
  aws iam list-instance-profiles --query "InstanceProfiles[?InstanceProfileId==\`$iam_instance_profile_id\`].Roles[].RoleName" --output text
}

instance_ssh() {
  if [ -z "$1" ] ; then echo "Usage: $FUNCNAME instance-id [user]"; return 1; fi
  local instance_id=$1
  local user=$2

  local instance_details=$(instance_ssh_details $instance_id)
  local keyname=$(echo "$instance_details" | awk '{print $1}');
  local ip=$(echo "$instance_details" | awk '{print $2}');
  local instance_name=$(echo "$instance_details" | awk '{print $3}');
  local instance_default_user=$(echo "$instance_details" | awk '{print $4}');

  local USERNAME=${user:-${instance_default_user:-${AWS_DEFAULT_USER:-root}}}
  echo "Connecting to $instance_id $instance_name"
  ssh \
    -t \
    -i ~/.ssh/$keyname \
    -o LogLevel=quiet \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -l $USERNAME \
    $ip
}

instance_ssh_details() {
  if [ -z "$1" ] ; then echo "Usage: $FUNCNAME stack [template]"; return 1; fi
  local instance_id=$1
  aws ec2 describe-instances --filters Name=instance-id,Values=$instance_id --query "
    Reservations[].Instances[0].[
      KeyName,
      PrivateIpAddress,
      join(\` \`, [Tags[?Key==\`Name\`].Value][] || [\`not-named\`]),
      join(\` \`, [Tags[?Key==\`default-user\`].Value][] || [\`\`])
    ]" --output text
}

instance_start() {
  if [ -z "$1" ] ; then echo "Usage: $FUNCNAME instance-id"; return 1; fi
  aws ec2 start-instances --instance-id $1
}

instance_stop() {
  if [ -z "$1" ] ; then echo "Usage: $FUNCNAME instance-id"; return 1; fi
  aws ec2 stop-instances --instance-id $1
}

instance_terminate() {
  aws ec2 modify-instance-attribute --attribute disableApiTermination --value false --instance-id $1
  aws ec2 terminate-instances --instance-id $1
}

instance_types() {
  aws ec2 describe-instances --filters Name=instance-state-name,Values=running --query "Reservations[].Instances[].[InstanceType]" --output text | sort | uniq -c
}

instance_userdata() {
  if [ -z "$1" ] ; then echo "Usage: $FUNCNAME instance-id"; return 1; fi
  local instance_id=$1
  aws ec2 describe-instance-attribute --attribute userData --instance-id $instance_id --query UserData --output text | base64 --decode
}

instance_volumes() {
  if [ -z "$1" ] ; then echo "Usage: $FUNCNAME instance_id [instance_id]"; return 1; fi
  local instance_ids=$@
  if local volume_ids=$(aws ec2 describe-instances --instance-ids $instance_ids --query "Reservations[].Instances[].BlockDeviceMappings[].Ebs[].VolumeId" --output text)
  then
    aws ec2 describe-volumes --volume-ids $volume_ids --query "Volumes[].$VOLUME_OUTPUT" --output text
  else
    >&2 echo "No volumes found"
  fi
}

instance_ip_private() {
  instance $@ |
    jq -r ".Reservations[].Instances[].PrivateIpAddress"
}

instance_ip_public() {
  instance $@ |
    jq -r ".Reservations[].Instances[].PublicIpAddress"
}
