#!/bin/bash

if [[ -z ${BMA_OUTPUT} ]]; then
  BMA_OUTPUT="text"
fi

if [[ -z ${INSTANCE_OUTPUT} ]]; then
  INSTANCE_OUTPUT="[
    InstanceId,
    State.Name,
    InstanceType,
    PrivateIpAddress,
    PublicIpAddress,
    join(\` \`, [Tags[?Key==\`Name\`].Value][]),
    join(\` \`, [Tags[?Key==\`contact\`].Value][]),
    LaunchTime
  ]"
fi

if [[ -z ${VOLUME_OUTPUT} ]]; then
  VOLUME_OUTPUT='[VolumeId, Size, VolumeType, State, CreateTime]'
fi

if [[ -z ${INSTANCE_OUTPUT} ]]; then
  INSTANCE_PROFILE_OUTPUT="[
    Profile
  ]"
fi

if [[ -z ${ELB_OUTPUT} ]]; then
  ELB_OUTPUT="[
    LoadBalancerName
  ]"
fi

if [[ -z ${ASG_OUTPUT} ]]; then
  ASG_OUTPUT="[
    AutoScalingGroupName
  ]"
fi

__bma_read_inputs() {
  # echo "${FUNCNAME}: \$@='${@}'" >&2
  if [[ -t 0 ]]; then
    # echo "${FUNCNAME}: STDIN is a terminal" >&2
    echo $@
  else
    # echo "${FUNCNAME}: STDIN is not a terminal" >&2
    local args="$@"
    echo "$(awk '{ print $1 }')" |
      sed "s/.$/& /"             |
      sed "s/$/$args/"
  fi
}

# vim: ft=sh
