#!/bin/bash
#
# aws-account-functions

# Returns the Account Alias
aws-account-alias() {
  aws iam list-account-aliases \
    --query AccountAliases     \
    --output text
}

# Returns AWS Account ID of caller
aws-account-id() {
  aws sts get-caller-identity --query Account --output text
}

# aws-account-each - Run command on multiple AWS Accounts
#
# Reads AWS Account IDs from STDIN
# Assumes an IAM Role on each account and runs command given as arguments
#
aws-account-each() {
  local aws_account_ids="$(__bma_read_inputs)"
  local cmd=$@
  local assumed_role_name="${AWS_PANOPTICON_ROLE_NAME:-SecurityAuditor}"
  [[ -z "${aws_account_ids}" ]] && __bma_usage "cmd # pipe in AWS_ACCOUNT_IDS" && return 1

  echo "#command=${cmd}"
  echo "#"

  for aws_account_id in $aws_account_ids; do
    local assumed_env=$(sts-assume-role "arn:aws:iam::${aws_account_id}:role/${assumed_role_name}")
    [[ -z "$assumed_env" ]] && continue # AWSCLI prints error if assuming role fails
    local aws_account_alias="$(export $assumed_env && aws-account-alias)"
    echo "#account=$aws_account_id alias=${aws_account_alias}"
    if ! output=$(export $assumed_env && eval "$cmd"); then
      : # something went wrong
    fi
    [ -z "$output" ] || printf '%s\n\n' "${output%$'\n'}"
  done
}

# aws-panopticon was previous name for aws-account-each()
aws-panopticon() {
  aws-account-each $@
}


# View a list of AWS_ACCOUNT_IDs in AWS Cost Explorer
#
aws-account-cost-explorer(){

  local accounts_formatted="%22$(__bma_read_inputs $@ | sed 's/ /%22,%22/g')%22"

  local cmd_open="$(hash xdg-open &> /dev/null && echo 'xdg-open' || echo 'open')"

  $cmd_open "https://console.aws.amazon.com/cost-reports/home?#/custom?groupBy=None&hasBlended=false&hasAmortized=false&excludeDiscounts=true&excludeTaggedResources=false&chartStyle=Group&granularity=Monthly&reportType=CostUsage&isTemplate=false&filter=%5B%7B%22dimension%22:%22LinkedAccount%22,%22values%22:%5B$accounts_formatted%5D,%22include%22:true,%22children%22:null%7D%5D&usageAs=usageQuantity&forecastTimeRangeOption=None&&timeRangeOption=YearToDate"

}


# View a list of AWS_ACCOUNT_IDs in AWS Cost Recommendations

aws-account-cost-recommendations(){

  local accounts_formatted="%22$(__bma_read_inputs | sed 's/ /%22,%22/g')%22"

  local cmd_open="$(hash xdg-open &> /dev/null && echo 'xdg-open' || echo 'open')"

  $cmd_open "https://console.aws.amazon.com/cost-reports/home?#/recommendations/rightsizing?isLoading&service=AmazonEC2&rightsizingType=%5B%22Terminate%22,%22Modify%22%5D&filter=%5B%7B%22dimension%22:%22LINKED_ACCOUNT%22,%22values%22:%5B$accounts_formatted%5D,%22include%22:true%7D%5D"

}
