#!/bin/bash
# set -eu -o pipefail # I source this file and don't want my shell to exit on error.
# shellcheck disable=SC2120

# azure-functions
#
# WARNING, an experiment - alpha! - do not use!
#
# I first used the `az cli` on 25 Nov 2022 so am only at the start of a 
# learning journey.
#
# Source this file in from bash terminal and enjoy the functions.
#
# az reference: https://learn.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest

# Wishlist
#
# - `az login` without opening GUI web browser. username/password is an option.
# - bash completion


# Notes
#
# az login : log in
# az account clear: log out all users
# az logout: only log out current user


# Shared Functions

function debug() {
  [[ -n $DEBUG ]] && printf "$1" >&2
}

__bma_read_filters-az() {

  # Construct a string to be passed to `grep -E`
  #
  #     $ __bma_read_filters foo bar baz
  #     foo|bar|baz

  ( IFS=$'|'; printf -- "$*" )
}

function columnise ()
{
    column -t -s$'\t'
}

function skim-stdin-tsv ()
{
    # XXX Update to quote items in output
    local skimmed_stdin="$([[ -t 0 ]] || awk -F$'\t' 'ORS=" " { print $1 }')";
    printf -- '%s %s' "$*" "$skimmed_stdin" | awk '{$1=$1;print}'
}

# Copied from bash-my-aws
function skim-stdin-bma() {

  # Append first token from each line of STDIN to argument list
  #
  # Implementation of `pipe-skimming` pattern.
  #
  #     $ stacks | skim-stdin foo bar
  #     foo bar huginn mastodon grafana
  #
  #     $ stacks
  #     huginn    CREATE_COMPLETE  2020-01-11T06:18:46.905Z  NEVER_UPDATED  NOT_NESTED
  #     mastodon  CREATE_COMPLETE  2020-01-11T06:19:31.958Z  NEVER_UPDATED  NOT_NESTED
  #     grafana   CREATE_COMPLETE  2020-01-11T06:19:47.001Z  NEVER_UPDATED  NOT_NESTED
  #
  # Typical usage within Bash-my-AWS functions:
  #
  #     local asg_names=$(skim-stdin "$@") # Append to arg list
  #     local asg_names=$(skim-stdin)      # Only draw from STDIN

  local skimmed_stdin="$([[ -t 0 ]] || awk 'ORS=" " { print $1 }')"

  printf -- '%s %s' "$*" "$skimmed_stdin" |
    awk '{$1=$1;print}'  # trim leading/trailing spaces

}

# Authentication functions

function az-account() {
  az account show \
    --query ' [[ name, user.name ]]' \
    --output tsv |
  columnise
}

function az-user() {
  az ad signed-in-user show
}

# az cache functions

function az-cache-items() {
  az cache list \
  --query '[].[
    resourceGroup,
    resourceType,
    name,
    lastSaved
    ]' \
  --output tsv
}

function az-cache-item() {
  # XXX We probably want to quote args
  # Create arguments from output of az-cache-items() (if present)
  local args_from_stdin
  args_from_stdin="$([[ -t 0 ]] || awk '{ print "--resource-group=" $1, " --resource-type=" $2, " --name=" $3 }')"
  if [[ -n $1 ]]; then # if command line args provided
    if [[ -n $1 && -n $2 && -n $3 ]]; then # if >= 3 args present
      local args_from_cmd
      args_from_cmd="--resource-group=$1 --resource-type=$2 --name=$3"
    fi
  fi
  local $arg_list
  arg_list=$(printf -- '%s\n%s' "$args_from_stdin" "$args_from_cmd" ) # | awk '{$1=$1;print}')  # trim leading/trailing spaces
  echo "$arg_list"
  while read -r line; do
    az cache show $line
  done <<< "$arg_list"
}

function az-cache-item-delete() {
  # XXX We probably want to quote args
  # Create arguments from output of az-cache-items() (if present)
  local args_from_stdin
  args_from_stdin="$([[ -t 0 ]] || awk '{ print "--resource-group=" $1, " --resource-type=" $2, " --name=" $3 }')"
  if [[ -n $1 ]]; then # if command line args provided
    if [[ -n $1 && -n $2 && -n $3 ]]; then # if >= 3 args present
      local args_from_cmd
      args_from_cmd="--resource-group=$1 --resource-type=$2 --name=$3"
    fi
  fi
  local $arg_list
  arg_list=$(printf -- '%s\n%s' "$args_from_stdin" "$args_from_cmd" ) # | awk '{$1=$1;print}')  # trim leading/trailing spaces
  while read -r line; do
    az cache delete $line
  done <<< "$arg_list"
}

# Location Functions

function locations(){
  local filters=$(__bma_read_filters-az $@);
  az account list-locations \
    --query '[].[
      name,
      displayName
    ]' \
    --output tsv |
  grep -E -- "$filters" |
  LC_ALL=C sort -t$'\t' -b -k 3 |
  columnise

}

function location() {

  local location=$(skim-stdin-tsv "$@")
  # XXX Check input is a valid location
  if [[ -z "$location" ]]; then
    az config get defaults.location \
      --only-show-errors            \
      --output tsv                  \
      --query "value"
  else
    az config set defaults.location="${location}" \
      --only-show-errors                          \
      --output tsv
  fi
}

function location-unset() {
    az config unset defaults.location
}

function location-each() {

  local locations
  if [[ -t 0 ]]; then
    locations=$(locations | awk -F$'\t' '{print $1}')
  else
    locations=$(awk 'ORS=" " { print $1 }')
  fi
  local old_azure_default_location
  old_azure_default_location="$(location)"
  local location
  for location in $locations; do
    location "$location"
    eval "$@" | sed "s/$/ #${location}/"
  done
  location "$old_azure_default_location"
}

## Resource Functions

function resource-groups() {
  local filters=$(__bma_read_filters-az $@);
  az group list \
    --query "[].[
      name,
      id,
      location
      ]" \
    --output tsv |
  grep -E -- "$filters" |
  LC_ALL=C sort -t$'\t' -b -k 5 |
  column -s$'\t' -t
}

function resource-group() {

  local group=$(skim-stdin-bma "$@")
  # XXX Check input is a valid location
  if [[ -z "$group" ]]; then
    az config get defaults.group \
      --only-show-errors         \
      --output tsv               \
      --query "value"
  else
    az config set defaults.group="${group}" \
      --only-show-errors                          \
      --output tsv
  fi
}

function resource-group-export() {

  local resource_group=$(skim-stdin-bma "$@")
  [[ -z $resource_group ]] && resource_group=$(resource-group)
   debug "\$resource_group=$resource_group"
  [[ -z $resource_group ]] && __bma_usage "resource_group [resource_group]" && return 1

  az group export --resource-group "$resource_group"
}

function resource-group-unset() {
    az config unset defaults.group
}

function resources() {
  local filters=$(__bma_read_filters-az $@);
  az resource list                           \
    --query "[].[
      name,
      resourceGroup,
      type,
      createdTime,
      changedTime]" \
    --output tsv |
  grep -E -- "$filters" |
  LC_ALL=C sort -t$'\t' -b -k 5 |
  column -s$'\t' -t
}

function resourceids() {
  local filters=$(__bma_read_filters-az $@);
  az resource list      \
    --query "[].[id] "  \
    --output tsv        |
  grep -E -- "$filters" |
  LC_ALL=C sort -t$'\t' -b -k 5 |
  column -s$'\t' -t
}


function resource-export() {

  local resources=$(skim-stdin-bma "$@")
   debug "\$resources=$resources"
  [[ -z $resources ]] && __bma_usage "resource [resource]" && return 1

  az group export --resource-ids $resources
}

## Service Principal Functions

function service-principals() {
  local filters=$(__bma_read_filters-az $@);
  az ad sp list \
    --query "[].[
      appId,
      appOwnerTenantId,
      appDisplayName
    ]" \
    --output tsv |
    grep -E -- "$filters" |
    LC_ALL=C sort -t$'\t' -b -k 3 |
    column -s$'\t' -t
}

## Subscription Functions

function subscriptions() {
  local filters=$(__bma_read_filters-az $@);
  az account list            \
    --query "[].[
      id,
      isDefault,
      state,
      name
    ]"                       \
    --output tsv             |
    grep -E -- "$filters"    |
    LC_ALL=C sort -t$'\t' -b -k 3    |
    column -s$'\t' -t
}

function subscription() {

  local subscription=$(skim-stdin-bma "$@")
  if [[ -z $subscription ]]; then
    az account show --query "name" --output tsv
  else
    az account set --subscription "$subscription"
  fi
}

function subscription-unset() {
    az config unset defaults.subscription
}

function subscription-each() {

  # Ported from BMA

  local subscriptions
  if [[ -t 0 ]]; then
    subscriptions=$(subscriptions | awk -F$'\t' '{print $1}')
  else
    subscriptions=$(awk 'ORS=" " { print $1 }')
  fi
  local old_default_subscription
  old_default_subscription="$(subscription | awk '{print $1}')"
  local subscription
  for subscription in $subscriptions; do
    subscription "$subscription"
    eval "$@" | sed "s/$/ #${subscription}/"
  done
  subscription "$old_default_subscription"
}

## Resource Specific Functions

## Front Door WAF Functions

function front-door-waf-policies() {
  local filters=$(__bma_read_filters-az $@);
  az network front-door waf-policy list \
    --output tsv \
    --query "[].[
      name,
      resourceGroup,
      resourceState
      ]" |
  grep -E -- "$filters" |
  LC_ALL=C sort -t$'\t' -b -k 1 |
  column -s$'\t' -t
}

function front-door-waf-policy-rules() {

  local policies=$(skim-stdin-bma "$@")
   debug "\$policies=$policies"
  [[ -z $policies ]] && __bma_usage "policy [policy]" && return 1

  local policy
  for policy in $policies; do
    az network front-door waf-policy rule list \
      --policy-name "$policy" \
      --output tsv \
      --query "[].[
        name,
        enabledState,
        priority,
        ruleType,
        action,
        '$policy',
        '$resource_group'
      ]" |
    LC_ALL=C sort -t$'\t' -b -k 1 |
    column -s$'\t' -t
  done
}

function front-door-waf-policy() {

  local policies=$(skim-stdin-bma "$@")
   debug "\$policies=$policies"
  [[ -z $policies ]] && __bma_usage "policy [policy]" && return 1

  local policy
  for policy in $policies; do
    az network front-door waf-policy show --name "$policy" --output json
  done
}

function front-door-waf-policy-rule-match-conditions() {

  local policy_name="${1}"
  shift 1
  local rule_names=$(skim-stdin "$@")

  if [[ -z $policy_name || -z $rule_names ]]; then
    echo "Usage: ${FUNCNAME[0]} POLICY_NAME RULE_NAME [RULE_NAME]" >&2
    return 1
  fi

  local rule_name
  for rule_name in $rule_names; do
    az network front-door waf-policy rule match-condition list \
      --policy-name "$policy_name"                             \
      --name "$rule_name"                                      \
      --query '[].[[
        join(`=`, [`operator`, operator]),
        join(`=`, [`matchVariable`, matchVariable]),
        join(`=`, [
          `matchValues`,
           to_string(length(matchValue))
        ]),
       `# view matches with front-door-waf-policy-rule-match-values()`
      ]][]'                                                       \
      --output tsv
  done
}

function front-door-waf-policy-rule-match-condition-values() {

  local policy_name="${1}"
  shift 1
  local rule_names=$(skim-stdin "$@")

  if [[ -z $policy_name || -z $rule_names ]]; then
    echo "Usage: ${FUNCNAME[0]} POLICY_NAME RULE_NAME [RULE_NAME]" >&2
    return 1
  fi

  local rule_name
  for rule_name in $rule_names; do
    az network front-door waf-policy rule match-condition list \
      --policy-name "$policy_name"                             \
      --name "$rule_name"                                      \
      --query '[0].[matchValue][]'                             \
      --output tsv
  done
}

function front-door-waf-policy-rule-delete() {

  local policy_name="${1:-}"
  shift
  local rule_names=$(skim-stdin-bma "$@")

  if [[ -z $policy_name || -z $rule_names ]]; then
    echo "Usage: front-door-waf-policy-rule-delete POLICY_NAME RULE_NAME [RULE_NAME]" >&2
    return 1
  fi

  echo "You are about to delete the following front-door WAF policy rules from $policy_name:"
  echo "$rule_names" | tr ' ' "\n" # | front-door-waf-policy-rules # XXX add when we have resourceGroup sorted
  [ -t 0 ] || exec </dev/tty # reattach keyboard to STDIN
  local regex_yes="^[Yy]$"
  read -p "Are you sure you want to continue? " -n 1 -r
  echo
  if [[ $REPLY =~ $regex_yes ]]
  then
    # XXX replace with `--ids` arg when we can generate resource IDs # it's easy
    for rule_name in $rule_names; do
      az network front-door waf-policy rule delete --policy-name wafPremium --name "${rule_name}"
    done
  fi
}

## AD Functions

function ad-users() {

  # Usage: ad-users REMOTE_STARTS_WITH_FILTER LOCAL_FILTER
  #
  # REMOTE_STARTS_WITH_FILTER: filters on start of userPrincipalName
  # - https://learn.microsoft.com/en-us/cli/azure/format-output-azure-cli
  #
  # Uses graph API - more functionaility than azcli but limited result count
  #
  # $ time ad-users | wc -l
  # 999
  # real    0m0.792s
  # user    0m0.311s
  # sys     0m0.047s
  #
  # [User Properties](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties)
  # [List Users](https://learn.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http)

  local filter_arg filters
  local output_format="${2:-tsv}" #  or json, table, etc
  local top_arg='&top=999' # max items to return # uncomment to enable
  if [[ -n $1 ]]; then
    filter_arg="&filter=startswith(userPrincipalName,'$1')"
    shift
  fi

  local url="https://graph.microsoft.com/beta/users?${top_arg}${filter_arg}&select=userPrincipalName,displayName,onPremisesSyncEnabled,mail"
  eval "az rest          \
    --method get         \
    --url \"$url\"         \
    --query \"value[].[
      userPrincipalName,
      displayName,
      join('=',['onPremisesSyncEnabled', to_string(onPremisesSyncEnabled)]),
      mail
    ]\" \
    --output $output_format"       |
  LC_ALL=C sort -t$'\t' -b -k 2 # | # Set to sort only when output is not set to JSON
  # column -s$'\t' -t # Disabled to preserve tabs
}

# Similar to ad-users but uses azcli with no limit on result count
#
# $ time ad-users-not-graph-api | wc -l
# 20820
# 
# real    0m50.309s
# user    0m15.158s
# sys     0m0.443s
#
function ad-users-not-graph-api() {

  # Usage: ad-users REMOTE_STARTS_WITH_FILTER LOCAL_FILTER
  #
  # REMOTE_STARTS_WITH_FILTER: filters on start of userPrincipalName
  # LOCAL_FILTER: grep results
  #
  # [User Properties](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties)
  # [List Users](https://learn.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http)

  local filter_arg filters
  if [[ -n $1 ]]; then
    filter_arg='--filter "startswith(userPrincipalName,'"'$1'"')"'
    shift
    local filters=$(__bma_read_filters-az $@);
  fi

  eval "az ad user list \
    ${filter_arg}       \
    --query '[].[
      userPrincipalName,
      displayName,
      mail
      ]'                \
    --output tsv"       |
  grep -E -- "$filters" |
  LC_ALL=C sort -t$'\t' -b -k 2 |
  column -s$'\t' -t
}

function ad-user-groups() {

  # List groups for AD User(s)
  #
  #     USAGE: ad-user-groups USER USER # object ID or principal name of the user
  #
  #     $ ad-users mike.bailey@bash-my-aws.org | ad-user-groups
  #     XXX
  #     XXX

  local users=$(skim-stdin "$@")
  [[ -z $users ]] && __bma_usage "ad-user-groups USER [USER]" && return 1

  local user
  for user in $users; do
    az ad user get-member-groups    \
      --id "$user"                  \
      --query "[].[
        id,
        displayName,
        '$user'
        ]"               \
      --output tsv                  |
      LC_ALL=C sort -t$'\t' -b -k 2 |
      column -s$'\t' -t
  done
}




function ad-apps() {

  # Usage: ad-users REMOTE_FILTER LOCAL_FILTER
  #
  # REMOTE_FILTER: filters on start of userPrincipalName
  # LOCAL_FILTER: grep results

  local filter_arg filters
  if [[ -n $1 ]]; then
    filter_arg='--filter "startswith(displayName,'"'$1'"')"'
    shift
    local filters=$(__bma_read_filters-az $@);
  fi

  eval "az ad app list  \
    ${filter_arg}       \
    --query '[].[
      appId,
      displayName,
      createdDateTime
      ]'                \
    --output tsv"       |
  grep -E -- "$filters" |
  LC_ALL=C sort -t$'\t' -b -k 3 |
  column -s$'\t' -t
}
