#!/bin/bash
#
# ecr-functions


ecr-repositories() {

  # List ECR Repositories

  local aws_account_id=$(__bma_read_inputs)
  local filters=$(__bma_read_filters $@)

  aws ecr describe-repositories \
      $([[ -n ${aws_account_id} ]] && echo --registry-id "${aws_account_id}") \
    --query "
      repositories[].[
        repositoryName,
        registryId,
        repositoryUri
      ]"                        \
    --output text       |
  grep -E -- "$filters" |
  LC_ALL=C sort -b -k 1 |
  column -s$'\t' -t
}


ecr-repository-images() {

  # List images for ECR Repositories

  if [[ $1 =~ registry ]]; then # XXX tidy this up!
    local registry_id=${1#registry=}
    shift
  fi
  local repository_names=$(__bma_read_inputs $@ )

  # XXX Display USAGE if no repository_names passed in

  local repository_name
  for repository_name in $repository_names; do
    echo '#'
    aws ecr describe-images                                         \
      $([[ -n $registry_id ]] && echo --registry-id "$registry_id") \
      --repository-name "$repository_name"                          \
      --output text                                                 \
      --query "
        imageDetails[].[
          repositoryName,
          registryId,
          join('=', ['BYTES',to_string(imageSizeInBytes)]),
          join('=', ['PUSHED_AT',to_string(imagePushedAt)]),
          join('=', ['DIGEST',to_string(imageDigest)]),
          join(',', [imageTags][])
        ]"                                           |
    LC_ALL=C sort -b -k 4                            |
    sed -E 's/DIGEST=.*:(.{12})\S*/\1/g' # short sha
  done |
  column -s$'\t' -t
}
