#!/bin/bash
#
# elb-functions

elbs() {
  # returns a list of ELBS
  local elb_names=$(__bma_read_inputs)
  local filters=$(__bma_read_filters $@)

  aws elb describe-load-balancers                                     \
    $([[ -n ${elb_names} ]] && echo --load-balancer-names $elb_names) \
    --query "LoadBalancerDescriptions[][ LoadBalancerName ]"          \
    --output text       |
  grep -E -- "$filters" |
  sort                  |
  column -s$'\t' -t
}

elb-dnsname(){
  local elb_names=$(__bma_read_inputs $@)
  [[ -z "${elb_names}" ]] && __bma_usage "load-balancer" && return 1

  local elb_name
  for elb_name in $elb_names; do
    aws elb describe-load-balancers    \
      --load-balancer-name ${elb_name} \
      --query "
        LoadBalancerDescriptions[][
          '${elb_name}',
          DNSName
        ]"                             \
      --output text                    |
      column -s$'\t' -t
  done 
}

elb-instances() {
  local elb_names=$(__bma_read_inputs $@)
  [[ -z "${elb_names}" ]] && __bma_usage "load-balancer" && return 1

  local elb_name
  for elb_name in $elb_names; do
    aws elb describe-instance-health   \
      --load-balancer-name ${elb_name} \
      --query "
        InstanceStates[][
            InstanceId,
            State,
            ReasonCode,
            '${elb_name}'
        ]"                             \
      --output text                    |
      column -s$'\t' -t
  done 
}

