#!/bin/bash
#
# instance-functions
#
# List, run, start, stop and ssh to Amazon AWS EC2 instances

source $(dirname ${BASH_SOURCE[0]})/shared.inc

instances() {
  # type: query
  # returns instance id's and the name tag.
  local inputs=$(__bma_read_inputs $@)

  if __bma_read_switches ${inputs} | grep ^--debug > /dev/null; then
    BMA_DEBUG=true
  else
    BMA_DEBUG=false
  fi

  local default_query='
    Reservations[].Instances[][
        InstanceId,
        ImageId,
        InstanceType,
        State.Name,
        [Tags[?Key==`Name`].Value][0][0],
        LaunchTime
    ]
  '

  local instance_ids=$(__bma_read_resources $inputs)
  local filters=$(__bma_read_switches $inputs | grep ^--filters | cut -d\  -f2-)
  local query=$(__bma_read_switches $inputs | grep ^--query | cut -d\  -f2-)
  local output=$(__bma_read_switches $inputs | grep ^--output | cut -d\  -f2-)

  if ${BMA_DEBUG}; then
    echo "inputs: ${inputs}"
    echo "instance_ids: ${instance_ids}"
    echo "filters: ${filters}"
    echo "query: ${query}"
    echo "output: ${output}"
  fi

  [[ -z $query ]] && local query=$default_query

  aws ec2 describe-instances                                            \
    $([[ -n ${instance_ids} ]] && echo --instance-ids ${instance_ids})  \
    $([[ -n ${filters} ]] && echo "--filters ${filters}")               \
    --query "${query}"                                                  \
    --output ${output:-"text"}
}

instance-asg() {
  local inputs="$(__bma_read_inputs $@)"
  [[ -z "$inputs" ]] && __bma_usage "instance-id [instance-id]" && return 1
  local query='
    Reservations[].Instances[][
      {
        "AutoscalingGroupName": [Tags[?Key==`aws:autoscaling:groupName`].Value][0][0],
        "InstanceId": InstanceId
      }
    ][]
  '
  instances ${inputs} --query ${query}
}

instance-console() {
  # detail
  local inputs=$(__bma_read_inputs $@)
  [[ -z "$inputs" ]] && __bma_usage "instance-id [instance-id]" && return 1
  for instance_id in $(__bma_read_resources ${inputs}); do
    echo Console output for EC2 Instance $instance_id
    aws ec2 get-console-output    \
      --instance-id $instance_id  \
      --query Output              \
      --output text
    echo
  done
}

instance-dns() {
  ## detail
  local inputs="$(__bma_read_inputs $@)"
  [[ -z "$inputs" ]] && __bma_usage "instance-id [instance-id]" && return 1
  local query='
    Reservations[].Instances[][
      {
        "InstanceId": InstanceId,
        "Private": PrivateDnsName,
        "Public": PublicDnsName
      }
    ][]
  '
  instances ${inputs} --query ${query}
}

instance-iam-profile() {
  ## detail
  local inputs="$(__bma_read_inputs $@)"
  [[ -z "$inputs" ]] && __bma_usage "instance-id [instance-id]" && return 1
  local query='
    Reservations[].Instances[][
      [
        InstanceId,
        IamInstanceProfile.Id
      ]
    ][]
  '
  instances ${inputs} --query ${query}
}

instance-ip() {
  ## detail
  local inputs="$(__bma_read_inputs $@)"
  [[ -z "$inputs" ]] && __bma_usage "instance-id [instance-id]" && return 1
  local query='
    Reservations[].Instances[][
      {
        "InstanceId": InstanceId,
        "Private": PrivateIpAddress,
        "Public": PublicIpAddress
      }
    ][]
  '
  instances ${inputs} --query ${query}
}

instance-ssh() {
  # XXX Does not work with input from STDIN

  # TODO: this may be cleaner
  #if [[ ! -t 0 ]] || [[ -z "$1" ]]; then
  #  __bma_usage "instance_id [login-template-file]"
  #  return 1
  #fi
  if ! [[ -t 0 ]]; then echo "Usage: $FUNCNAME instance_id [login]"; return 1; fi
  if [ -z "$1" ] ; then echo "Usage: $FUNCNAME instance_id [login]"; return 1; fi

  local instance_id=$1
  if [ -n "$2" ]; then local user="$2"; fi
  local instance_details="$(instance-ssh-details $1)"
  local instance_id=$(echo $instance_details | awk '{print $1}');
  local keyname=$(echo $instance_details | awk '{print $2}');
  local private_ip=$(echo $instance_details | awk '{print $3}');
  local instance_name=$(echo $instance_details | awk '{print $4}');
  local instance_default_user=$(echo $instance_details | awk '{print $5}');

  local USERNAME=${user:-${instance_default_user:-${AWS_DEFAULT_USER:-root}}}
  echo "Connecting to EC2 Instance $instance_id '$instance_name'" 2>&1

  ssh                                  \
    -t                                \
    -i ${BMA_SSH_DIR:-~/.ssh/}$keyname \
    -o LogLevel=error                  \
    -o StrictHostKeyChecking=no        \
    -o UserKnownHostsFile=/dev/null    \
    -l $USERNAME                       \
    $private_ip
}

instance-ssh-details() {
  local inputs="$(__bma_read_inputs $@)"
  [[ -z "${inputs}" ]] && __bma_usage "instance_id" && return 1

  local query='
    Reservations[].Instances[][
      InstanceId,
      KeyName,
      PrivateIpAddress,
      join(` `, [Tags[?Key==`Name`].Value][] || [`not-named`]),
      join(` `, [Tags[?Key==`default-user`].Value][] || [``])
    ]
  '
  instances ${inputs} --query ${query}
}

instance-stack() {
  local inputs="$(__bma_read_inputs $@)"
  [[ -z "$inputs" ]] && __bma_usage "instance-id [instance-id]" && return 1
  local query='
    Reservations[].Instances[][
      [
        [Tags[?Key==`aws:cloudformation:stack-name`].Value][0][0],
        InstanceId
      ]
    ][]
  '
  instances ${inputs} --query ${query}
}

instance-start() {
  local inputs="$(__bma_read_inputs $@)"
  [[ -z "$inputs" ]] && __bma_usage "instance-id" && return 1
  aws ec2 start-instances --instance-id $inputs
}

instance-state() {
  ## detail
  local inputs="$(__bma_read_inputs $@)"
  [[ -z "$inputs" ]] && __bma_usage "instance-id [instance-id]" && return 1
  local query='
    Reservations[].Instances[][
      {
        "InstanceId": InstanceId,
        "State": State.Name
      }
    ][]
  '
  instances ${inputs} --query ${query}
}

instance-stop() {
  local inputs="$(__bma_read_inputs $@)"
  [[ -z "$inputs" ]] && __bma_usage "instance-id" && return 1
  aws ec2 stop-instances --instance-id $inputs
}

# Replaces two older functions
#
# instances_with_tag() # instance_tags | grep expiry=
# instances_without_tag() # instance_tags | grep -v expiry=
#
instance-tags() {
  local inputs="$(__bma_read_inputs $@)"
  [[ -z "$inputs" ]] && __bma_usage "instance-id [instance-id]" && return 1
  local query='
    Reservations[].Instances[].[
      InstanceId,
      join(`" "`, Tags[].[join(`=`,[Key,Value])][])
    ]
  '
  instances ${inputs} --query ${query}
}

instance-terminate() {
  aws ec2 modify-instance-attribute --attribute disableApiTermination --value false --instance-id $1
  aws ec2 terminate-instances --instance-id $1
}

instance-type() {
  local inputs="$(__bma_read_inputs $@)"
  [[ -z "$inputs" ]] && __bma_usage "instance-id [instance-id]" && return 1
  local query='
    Reservations[].Instances[][
      [
        InstanceId,
        InstanceType
      ]
    ][]
  '
  instances ${inputs} --query ${query}
}

instance-userdata() {
  # detail
  local inputs=$(__bma_read_inputs $@)
  [[ -z "$inputs" ]] && __bma_usage "instance-id [instance-id]" && return 1
  for instance_id in $(__bma_read_resources ${inputs}); do
    aws ec2 describe-instance-attribute \
      --attribute userData              \
      --instance-id $instance_id        \
      --query UserData                  \
      --output text                     |
        base64 --decode
  done
}

instance-volumes() {
  local inputs=$(__bma_read_inputs $@)
  [[ -z "$inputs" ]] && __bma_usage "instance-id [instance-id]" && return 1
  local query='
    Reservations[].Instances[][
        InstanceId,
        join(` `, BlockDeviceMappings[].Ebs[].VolumeId)
    ][]
  '
  instances ${inputs} --query ${query}
}

instance-vpc() {
  local inputs=$(__bma_read_inputs $@)
  [[ -z "$inputs" ]] && __bma_usage "instance-id [instance-id]" && return 1
  local query='
    Reservations[].Instances[][
        VpcId,
        InstanceId
    ][]
  '
  instances ${inputs} --query ${query}
}

#instance-role() {
#  local inputs=$(__bma_read_inputs $@ | base64 -D)
#
#  local query='
#    Reservations[].Instances[][
#      {
#        "AutoscalingGroupName": [Tags[?Key==`aws:autoscaling:groupName`].Value][0][0],
#        "InstanceId": InstanceId
#      }
#    ][]
#  '
#  instances ${inputs} --query ${query}
#
#
#
#  if [ -z "$1" ] ; then echo "Usage: $FUNCNAME instance_id"; return 1; fi
#  local instance_id=$1
#  local profile_id=$(aws ec2 describe-instances --instance-id $instance_id \
#    --query "Reservations[].Instances[].IamInstanceProfile.Id"             \
#    --output text)
#  aws iam list-instance-profiles                                                     \
#    --query "InstanceProfiles[?InstanceProfileId==\`$profile_id\`].Roles[].RoleName" \
#    --output text
#}


# vim: ft=sh
