#!/bin/bash
#
# miscellaneous functions that don't belong anywhere else

regions() {
  aws ec2 describe-regions --query "Regions[].[RegionName]" --output text | sort
}

region-each() {
  local old_aws_default_region="$AWS_DEFAULT_REGION"
  for AWS_DEFAULT_REGION in $(regions); do
    $@ | sed "s/$/ #${AWS_DEFAULT_REGION}/"
  done
  AWS_DEFAULT_REGION="$old_aws_default_region"
}

region() {
  local inputs=$(__bma_read_inputs $@)
  if [[ -z "$inputs" ]]; then
    echo "${AWS_DEFAULT_REGION:-'AWS_DEFAULT_REGION not set'}"
  else
    AWS_DEFAULT_REGION="$inputs"
  fi
}

aws-account-alias() {
  aws iam list-account-aliases --query AccountAliases --output text
}
