#!/bin/bash
# shellcheck disable=SC2155
#
# rds-functions
#
# Amazon AWS RDS database instances & clusters

# This is the second function refering to a type of `instance`
# Perhaps EC2 `instance` functions should be aliased to `ec2-instances`
# The original names would be deprecated but still supported for some time.

rds-db-instances() {

  # List RDS Database Instances

  # Tip: Filter on whether DB is in cluster with: `awk -F'\t' '$6 != "None"'`

  local filters=$(__bma_read_filters "$@")

  aws rds describe-db-instances \
    --output text               \
    --query "DBInstances[].[
        DBInstanceIdentifier,
	      DBInstanceClass,
        Engine,
        EngineVersion,
        DBInstanceStatus,
        DBName,
      	MultiAZ,
        DBClusterIdentifier
      ]"                |
  sed 's/True$/MultiAZ/g' | sed 's/False$//' |
  grep -E -- "$filters" |
  LC_ALL=C sort -b -k 1 |
    columnise
}



rds-db-clusters() {

  # List RDS Database Clusters

  local filters=$(__bma_read_filters "$@")

  aws rds describe-db-clusters \
    --output text              \
    --query "DBClusters[].[
        DBClusterIdentifier,
        Engine,
        EngineVersion,
        Status,
        ClusterCreateTime
      ]"                |
  grep -E -- "$filters" |
  LC_ALL=C sort -b -k 5 |
    columnise
}
