#!/bin/bash
#
# internal-functions
#
# Used by bash-my-aws functions to work with stdin and arguments.

__bma_read_char_stdin() {
  if [ -t 0 ]; then
    saved_tty_settings=$(stty -g)
    stty -icanon min 1 time 0
    eval "$1=\$(dd bs=1 count=1 2> /dev/null)"
    stty "$saved_tty_settings"
  else
    eval "$1=n"
  fi
}

__bma_read_inputs() {
  echo $(__bma_read_stdin) $@ |
    sed -E 's/\ +$//'         |
    sed -E 's/^\ +//'
}

__bma_read_stdin() {
  [[ -t 0 ]] ||
    cat                  |
      awk '{ print $1 }' |
      tr '\n' ' '        |
      sed 's/\ $//'
}

# Construct a string to be passed to `grep -E`
__bma_read_filters() {
  local IFS_SAVED="$IFS"; IFS=$'|'
  printf -- "$*"
  IFS=$IFS_SAVED
}

__bma_error() {
  echo "ERROR: $@" > /dev/stderr
  return 1
}

__bma_usage() {
  echo "USAGE: ${FUNCNAME[1]} $@" > /dev/stderr
}

## vim: ft=sh
