#!/bin/bash
#
# vpc-functions

source $(dirname ${BASH_SOURCE[0]})/shared.inc

vpcs() {
  local vpc_ids="$(__bma_read_inputs $@)"

  aws ec2 describe-vpcs \
    $([[ -n ${vpc_ids} ]] && echo --vpc-ids ${vpc_ids})     \
    --query 'Vpcs[].[
      [VpcId, 
      ((IsDefault==`false`)&&`not-default`)||`default-vpc`, 
      Tags[?Key==`Name`].Value || [`not-named`],
      CidrBlock,
      Tags[?Key==`aws:cloudformation:stack-name`].Value, 
      Tags[?Key==`version`].Value][]
      ][]'                                                  \
    --output text                                           |
    column -s$'\t' -t
}
